# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
QT += core network gui widgets
TARGET = example
DESTDIR = "../bin"
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
INCLUDEPATH+= ../include
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(example.pri)
