#ifndef TESTMODULE_GLOBAL_H
#define TESTMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTMODULE_LIBRARY)
#  define TESTMODULE_EXPORT Q_DECL_EXPORT
#else
#  define TESTMODULE_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTMODULE_GLOBAL_H
